### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by lededje** [richelbilderbeek/CityOfThieves#13]
Love the project, really keen to get it on my ds, please can you add installation instructions?

**Comment by richelbilderbeek** [comment]
The Travis CI configuration file, [.travis.yml](https://github.com/richelbilderbeek/CityOfThieves/blob/master/.travis.yml), shows whatever needs to be done to install all versions. If you'd need more info, please re-open this Issue.

**Comment by richelbilderbeek** [comment]
P.S. You can download the NDS file [here](http://richelbilderbeek.nl/GameCityOfThievesNds.zip). Feedback is always welcome.
