### ISSUE TITLE
Jesper claims the OR from 201.txt should be reflected in all_needed_to_slay_zanbar_bone in 156.txt (and elsewhere)

### ISSUE THREAD

**Issue by wdoekes** [richelbilderbeek/CityOfThieves#15]
Hi! See subject.

Speed-running the game is not possible if you're required to fetch useless items. Consider making it a user-made choice instead? So the player can decide for himself whether he has enough items.

Cheers, and thanks for the game!

**Comment by richelbilderbeek** [comment]
Thanks for the suggestion! If and only if I find a volunteer, I will add a special speedrun mode.Maybe Jesper is up for this?

If one would wonder how many options there are for speedrunning, the full graph of the game is [here](https://github.com/richelbilderbeek/CityOfThieves/blob/master/Misc/Graph.png).

**Comment by wdoekes** [comment]
A volunteer to code the change? Or a volunteer to test the changes? :grimacing:

**Comment by richelbilderbeek** [comment]
The first. Volunteers are easy to find :smile:

**Comment by richelbilderbeek** [comment]
For now, I keep the code reflecting the real book as such.
