### ISSUE TITLE
Qmake error when trying to build the CLI only version

### ISSUE THREAD

**Issue by sandervankasteel** [richelbilderbeek/CityOfThieves#17]
I'm currently trying to get the console version of CityOfThieves wrapped up as an Arch Linux AUR package, but I'm running into some issues when I try to compile City of Thieves. 

When I try to execute `./build_console` I am running into two issues;

1. This is immediately the warning that popups in my console `***Unknown option -qt=qt5`. I'm not really sure, if that's an error that can be ignored (because I am build the console version instead of a GUI version of it).
2. The build script seems to stop immediately with the following message `make: *** No targets specified and no makefile found.  Stop.` 

Am I missing some dependency or do you have some tips on how to debug this ?

My complete build log can be found here: https://gist.github.com/sandervankasteel/f67295564c205c902231e6ab8ca8867f

**Comment by richelbilderbeek** [comment]
Thanks for the detailed report!

> Am I missing some dependency or do you have some tips on how to debug this ?

Yes, you will really need to install the Qt5 qmake version (the deb is `qt5-qmake`)`. The warning shares that no Makefile is created without it :grin:

Happy to help if there's something more :+1:

**Comment by sandervankasteel** [comment]
I just some extra digging, turns out if I remove the `-qt=qt5` parameter, I can now successfully build the application. On Arch I am using Qmake version 3.1 with Qt 5.13.1 and I did notice that you are using Qt 5.9.5 on Travis, so there might a a change of parameters between those versions. So that might be worth checking out it. 

For the moment, this only appears to be an issue on the package / building side of things so I will fix it on my end. 

For reference, the output of my `qmake -v`;
```
sander@titan ‹ master ● › : ~/Development/cityofthieves-cli/src/CityOfThieves-1.2/Console
[0] % qmake -v
QMake version 3.1
Using Qt version 5.13.1 in /usr/lib
```

**Comment by richelbilderbeek** [comment]
Cool, if it works, it works!

There are some cases Qt5 *is* mandatory, apparently, here it's not. Enjoy! :+1:

**Comment by sandervankasteel** [comment]
Closing the issue because everything works as it should be. :+1:
