### ISSUE TITLE
About screen seems to be out-of-date

### ISSUE THREAD

**Issue by sandervankasteel** [richelbilderbeek/CityOfThieves#23]
I just saw that you released a new version, so I decided to update the AUR package. But your about screen still says 1.7.

![image](https://user-images.githubusercontent.com/17492906/97106635-3f37fe00-16c3-11eb-8a7b-b81902c9843a.png)

**Comment by richelbilderbeek** [comment]
Well spotted! I will fix it now :+1:

**Comment by richelbilderbeek** [comment]
@sandervankasteel it's fixed! Again, thanks for the bugreport :+1:

**Comment by sandervankasteel** [comment]
You are welcome! :+1:
