### ISSUE TITLE
Show inventory items in desktop version

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/CityOfThieves#8]
_From @richelbilderbeek on July 26, 2015 17:1_

Added them by name. Add pictures iff @modanung really likes to make these.

![itemsin](https://cloud.githubusercontent.com/assets/2098230/8895001/d55feb2c-33ca-11e5-83c6-43269b4dc187.png)

_Copied from original issue: richelbilderbeek/HetRoversnest#26_

**Comment by ghost** [comment]
Initial versions of items mentioned in screenshot:
<img width="513" alt="items" src="https://cloud.githubusercontent.com/assets/7316241/14942836/d2127fd6-0fc8-11e6-91e2-5e543eec77b1.png">

**Comment by richelbilderbeek** [comment]
Awesome!

**Comment by richelbilderbeek** [comment]
I'm closing this Issue; it went stale.
